# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Sisurbano
                                 A QGIS plugin
 Cáculo de indicadores urbanos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-16
        copyright            : (C) 2019 by LlactaLAB
        email                : johnatan.astudillo@ucuenca.edu.ec
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Johnatan Astudillo'
__date__ = '2019-09-16'
__copyright__ = '(C) 2019 by LlactaLAB'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsProcessingMultiStepFeedback,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFeatureSink)
from .ZProcesses import *
from .Zettings import *
from .ZHelpers import *

pluginPath = os.path.split(os.path.split(os.path.dirname(__file__))[0])[0]

class IA03Compactness(QgsProcessingAlgorithm):
    """
    Mide la intensidad edificatoria del territorio; donde el resultado
    representa la altura media de edificación. Relación entre el volumen
    total edificado y la superficie de suelo del área de estudio.
    Formula: Volumen edificado en m3 /
    Superficie total del área de estudio en m2
    """ 
    CADASTRE = 'CADASTRE'
    CONSTRUCTION_AREA = 'CONSTRUCTION_AREA'
    FLOORS = 'FLOORS'
    CELL_SIZE = 'CELL_SIZE'
    OUTPUT = 'OUTPUT'
    STUDY_AREA_GRID = 'STUDY_AREA_GRID'
 

    def initAlgorithm(self, config):
        currentPath = getCurrentPath(self)
        FULL_PATH = buildFullPathName(currentPath, nameWithOuputExtension(NAMES_INDEX['IA03'][1]))    

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.CADASTRE,
                self.tr('Catastro'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.CONSTRUCTION_AREA,
                self.tr('Area de construcción'),
                'Area Cons', 'CADASTRE'
            )
        )      

        self.addParameter(
            QgsProcessingParameterField(
                self.FLOORS,
                self.tr('Pisos de construcción'),
                'Pisos cons', 'CADASTRE'
            )
        )   

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.STUDY_AREA_GRID,
                self.tr(TEXT_GRID_INPUT),
                [QgsProcessing.TypeVectorPolygon],
                '', OPTIONAL_GRID_INPUT
            )
        )

        if OPTIONAL_GRID_INPUT:
            self.addParameter(
                QgsProcessingParameterNumber(
                    self.CELL_SIZE,
                    self.tr('Tamaño de la malla'),
                    QgsProcessingParameterNumber.Integer,
                    P_CELL_SIZE, False, 1, 99999999
                )
            )   

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Salida'),
                QgsProcessing.TypeVectorAnyGeometry,
                str(FULL_PATH)                
            )
        )

    def processAlgorithm(self, params, context, feedback):
        steps = 0
        totalStpes = 8
        fieldConstructionArea = str('"'+params['CONSTRUCTION_AREA']+'"')
        # todos tienen un piso. El area de contruccion esta tomado por pisos
        fieldFloorsNumber = str('"'+params['FLOORS']+'"')
        heightFloor = '3'

        feedback = QgsProcessingMultiStepFeedback(totalStpes, feedback)

        steps = steps+1
        feedback.setCurrentStep(steps)
        if not OPTIONAL_GRID_INPUT: params['CELL_SIZE'] = P_CELL_SIZE        
        grid, isStudyArea = buildStudyArea(params['CELL_SIZE'], params['CADASTRE'],
                                           params['STUDY_AREA_GRID'],
                                           context, feedback)
        gridNeto = grid

        # multiplicar area de contruccion por la altura
        # base del area de cada piso (al parecer porque el ac > at)
        steps = steps+1
        feedback.setCurrentStep(steps)
        formulaBuiltVolume = 'coalesce(' + fieldConstructionArea + ' * ' + heightFloor + ' * ' + fieldFloorsNumber + ', 0)'
        print(formulaBuiltVolume)
        cadastreBuiltVolume = calculateField(params['CADASTRE'], 'built_volume',
                                             formulaBuiltVolume,
                                             context,
                                             feedback)


        # obtener la proporción del constucción en base al área del segmento
        steps = steps+1
        feedback.setCurrentStep(steps)
        blocks = calculateArea(cadastreBuiltVolume['OUTPUT'], 'area_bloc', context,
                               feedback)


        steps = steps+1
        feedback.setCurrentStep(steps)
        segments = intersection(blocks['OUTPUT'], gridNeto['OUTPUT'],
                                'area_bloc;built_volume',
                                'id_grid;area_grid',
                                context, feedback)


        steps = steps+1
        feedback.setCurrentStep(steps)
        segmentsArea = calculateArea(segments['OUTPUT'],
                                   'area_seg',
                                   context, feedback)

        steps = steps+1
        feedback.setCurrentStep(steps)
        formulaPopulationSegments = '(area_seg/area_bloc) * built_volume'
        compactnessForSegments = calculateField(segmentsArea['OUTPUT'], 'compact_seg',
                                          formulaPopulationSegments,
                                          context,
                                          feedback)


        steps = steps+1
        feedback.setCurrentStep(steps)
        gridIntersectCadaster = joinByLocation(gridNeto['OUTPUT'],
                                               compactnessForSegments['OUTPUT'],
                                               'compact_seg',
                                               [INTERSECTA], [SUM],
                                               UNDISCARD_NONMATCHING,
                                               context,
                                               feedback)  
        steps = steps+1
        feedback.setCurrentStep(steps)
        formulaCompactness = 'coalesce(compact_seg_sum / area_grid, 0)'
        compactness = calculateField(gridIntersectCadaster['OUTPUT'], NAMES_INDEX['IA03'][0],
                                   formulaCompactness,
                                   context,
                                   feedback, params['OUTPUT'])

        return compactness

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        #return {self.OUTPUT: dest_id}

    def icon(self):
        return QIcon(os.path.join(pluginPath, 'sisurbano', 'icons', 'compact2.png'))

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'A03 Compacidad absoluta'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'A Ambiente construido'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return IA03Compactness()

    def shortHelpString(self):
        return  "<b>Descripción:</b><br/>"\
                "<span>Mide la intensidad edificatoria del territorio; donde el resultado representa la altura media de edificación. Relación entre el volumen total edificado y la superficie de suelo del área de estudio.</span>"\
                "<br/><br/><b>Justificación y metodología:</b><br/>"\
                "<span>Para el cálculo se considera una altura de 3m por piso.</span>"\
                "<br/><br/><b>Formula:</b><br/>"\
                "<span>Volumen edificado en m3 / Superficie total en m2</span><br/>"
