# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Sisurbano
                                 A QGIS plugin
 Cáculo de indicadores urbanos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-16
        copyright            : (C) 2019 by LlactaLAB
        email                : johnatan.astudillo@ucuenca.edu.ec
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Johnatan Astudillo'
__date__ = '2019-09-23'
__copyright__ = '(C) 2019 by LlactaLAB'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsProcessingMultiStepFeedback,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFeatureSink)
from .ZProcesses import *
from .Zettings import *
from .ZHelpers import *

#pluginPath = os.path.split(os.path.split(os.path.dirname(__file__))[0])[0]

class IB06AgriculturalGrove(QgsProcessingAlgorithm):
    """
    Mide la capacidad de un territorio de contener actividades
    agrícolas o huertos en relación con el total de la población.
    Formula: Superficie de espacios agrícolas y huertos en m2 en el área de estudio / Población total en el área de estudio
    """
    AGRICULTRURAL = 'AGRICULTRURAL'
    BLOCKS = 'BLOCKS'
    FIELD_POPULATION = 'FIELD_POPULATION'
    # FIELD_HOUSING = 'FIELD_HOUSING'
    CELL_SIZE = 'CELL_SIZE'    
    OUTPUT = 'OUTPUT'
    STUDY_AREA_GRID = 'STUDY_AREA_GRID'    

    def initAlgorithm(self, config):
        currentPath = getCurrentPath(self)
        FULL_PATH = buildFullPathName(currentPath, nameWithOuputExtension(NAMES_INDEX['IB06'][1]))            

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.BLOCKS,
                self.tr('Manzanas'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.FIELD_POPULATION,
                self.tr('Población'),
                'poblacion', 'BLOCKS'
            )
        )      

        # self.addParameter(
        #     QgsProcessingParameterField(
        #         self.FIELD_HOUSING,
        #         self.tr('Viviendas'),
        #         'viviendas', 'BLOCKS'
        #     )
        # )        


        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.STUDY_AREA_GRID,
                self.tr(TEXT_GRID_INPUT),
                [QgsProcessing.TypeVectorPolygon],
                '', OPTIONAL_GRID_INPUT
            )
        )         

        if OPTIONAL_GRID_INPUT:
            self.addParameter(
                QgsProcessingParameterNumber(
                    self.CELL_SIZE,
                    self.tr('Tamaño de la malla'),
                    QgsProcessingParameterNumber.Integer,
                    P_CELL_SIZE, False, 1, 99999999
                )
            )          

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.AGRICULTRURAL,
                self.tr('Areas verdes'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Salida'),
                QgsProcessing.TypeVectorAnyGeometry,
                str(FULL_PATH)                
            )
        )

    def processAlgorithm(self, params, context, feedback):
        totalStpes = 13
        fieldPopulation = params['FIELD_POPULATION']

        feedback = QgsProcessingMultiStepFeedback(totalStpes, feedback)

        blocks = calculateArea(params['BLOCKS'], 'area_bloc', context,
                               feedback)

        steps = 0 + 1
        feedback.setCurrentStep(steps)
        if not OPTIONAL_GRID_INPUT: params['CELL_SIZE'] = P_CELL_SIZE
        grid, isStudyArea = buildStudyArea(params['CELL_SIZE'], params['BLOCKS'],
                                           params['STUDY_AREA_GRID'],
                                           context, feedback)
        gridNeto = grid  

        steps += 1
        feedback.setCurrentStep(steps)
        segments = intersection(
            blocks['OUTPUT'],
            gridNeto['OUTPUT'],
            f'area_bloc;{fieldPopulation}',
            'id_grid;area_grid',
            context,
            feedback,
        )

        steps += 1
        feedback.setCurrentStep(steps)
        segmentsArea = calculateArea(segments['OUTPUT'],
                                     'area_seg',
                                     context, feedback)

        steps += 1
        feedback.setCurrentStep(steps)
        formulaPopulationSegments = f'(area_seg/area_bloc) * {fieldPopulation}'
        populationForSegments = calculateField(segmentsArea['OUTPUT'], 'pop_seg',
                                               formulaPopulationSegments,
                                               context,
                                               feedback)

          # Haciendo el buffer inverso aseguramos que los segmentos
          # quden dentro de la malla
        steps += 1
        feedback.setCurrentStep(steps)
        populationForSegmentsFixed = makeSureInside(populationForSegments['OUTPUT'],
                                                    context,
                                                    feedback)

        steps += 1
        feedback.setCurrentStep(steps)
        gridNetoAndSegments = joinByLocation(gridNeto['OUTPUT'],
                                             populationForSegmentsFixed['OUTPUT'],
                                             'pop_seg',                                   
                                              [CONTIENE], [SUM],
                                              UNDISCARD_NONMATCHING,
                                              context,
                                              feedback)  


          # CALCULAR AREA AGRICULTURA
        steps += 1
        feedback.setCurrentStep(steps)
        agriPerBlocks = intersection(params['AGRICULTRURAL'], gridNeto['OUTPUT'],
                                      [],
                                      [],
                                      context, feedback)    



        steps += 1
        feedback.setCurrentStep(steps)
        agriArea = calculateArea(agriPerBlocks['OUTPUT'],
                                  'area_agri',
                                  context, feedback)


        steps += 1
        feedback.setCurrentStep(steps)
        agriAreaFixed = makeSureInside(agriArea['OUTPUT'],
                                        context,
                                        feedback)    

        steps += 1
        feedback.setCurrentStep(steps)
        agriAreaAndPopulation = joinByLocation(gridNetoAndSegments['OUTPUT'],
                                                agriAreaFixed['OUTPUT'],
                                                ['area_agri','pop_seg'],
                                                [CONTIENE], [SUM],
                                                UNDISCARD_NONMATCHING,                              
                                                context,
                                                feedback)


        steps += 1
        feedback.setCurrentStep(steps)
        formulaSurfacePerHab = 'coalesce(area_agri_sum/pop_seg_sum, 0)'
        return calculateField(
            agriAreaAndPopulation['OUTPUT'],
            NAMES_INDEX['IB06'][0],
            formulaSurfacePerHab,
            context,
            feedback,
            params['OUTPUT'],
        )


        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        #return {self.OUTPUT: dest_id}

    def icon(self):
        return QIcon(os.path.join(pluginPath, 'grass.png'))

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'B06 Superficie agrícola y huertos'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'B Ambiente biofísico'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return IB06AgriculturalGrove()

    def shortHelpString(self):
        return  "<b>Descripción:</b><br/>"\
                "<span>Mide la capacidad de un territorio de contener actividades agrícolas o huertos en relación con el total de la población.</span>"\
                "<br/><br/><b>Justificación y metodología:</b><br/>"\
                "<span></span>"\
                "<br/><br/><b>Formula:</b><br/>"\
                "<span>Superficie de espacios agrícolas y huertos en m2 en el área de estudio / Población total en el área de estudio<br/>"          

