# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Sisurbano
                                 A QGIS plugin
 Cáculo de indicadores urbanos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-16
        copyright            : (C) 2019 by LlactaLAB
        email                : johnatan.astudillo@ucuenca.edu.ec
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Johnatan Astudillo'
__date__ = '2020-01-14'
__copyright__ = '(C) 2019 by LlactaLAB'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsProcessingMultiStepFeedback,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFeatureSink)
from .ZProcesses import *
from .Zettings import *
from .ZHelpers import *
import numpy as np
import pandas as pd
import tempfile
import subprocess

#pluginPath = os.path.split(os.path.split(os.path.dirname(__file__))[0])[0]

class ID02HomesConstructiveDeficiencies(QgsProcessingAlgorithm):
    """
    Mide el porcentaje de viviendas que presentan carencias constructivas.
    Se define carencia constructiva cuando el estado de la cubierta, paredes y
    piso presentan deterioro o daño estructural que son un peligro inminente
    para los habitantes de la vivienda.
    Formula: (Viviendas con carencias / Total de viviendas)*100
    """

    BLOCKS = 'BLOCKS'
    DPA_MAN = 'DPA_MAN'
    CENSO_VIVIENDA = 'CENSO_VIVIENDA'
    # CENSO_POBLACION = 'CENSO_POBLACION'
    # CENSO_HOGAR = 'CENSO_HOGAR'
    CELL_SIZE = 'CELL_SIZE'
    OUTPUT = 'OUTPUT'
    STUDY_AREA_GRID = 'STUDY_AREA_GRID'
    CURRENT_PATH = 'CURRENT_PATH'    

    def initAlgorithm(self, config):
        currentPath = getCurrentPath(self)
        self.CURRENT_PATH = currentPath        
        FULL_PATH = buildFullPathName(currentPath, nameWithOuputExtension(NAMES_INDEX['ID02'][1]))

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.BLOCKS,
                self.tr('Manzanas'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.DPA_MAN,
                self.tr('DPA Manzanas'),
                'dpa_manzan', 'BLOCKS'
            )
        )           
      

        self.addParameter(
            QgsProcessingParameterFile(
                self.CENSO_VIVIENDA,
                self.tr('Censo vivienda'),
                extension='csv',
                defaultValue=''
            )
        )           

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.STUDY_AREA_GRID,
                self.tr(TEXT_GRID_INPUT),
                [QgsProcessing.TypeVectorPolygon],
                '', OPTIONAL_GRID_INPUT
            )
        )


        if OPTIONAL_GRID_INPUT:
            self.addParameter(
                QgsProcessingParameterNumber(
                    self.CELL_SIZE,
                    self.tr('Tamaño de la malla'),
                    QgsProcessingParameterNumber.Integer,
                    P_CELL_SIZE, False, 1, 99999999
                )
            )          


        # self.addParameter(
        #     QgsProcessingParameterNumber(
        #         self.NUMBER_HABITANTS,
        #         self.tr('Por cada número de habitantes'),
        #         QgsProcessingParameterNumber.Integer,
        #         100000, False, 1, 99999999
        #     )
        # )   

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Salida'),
                QgsProcessing.TypeVectorAnyGeometry,
                str(FULL_PATH)
            )
        )
        

    def processAlgorithm(self, params, context, feedback):
        totalStpes = 17
        fieldDpaMan = params['DPA_MAN']
        # fieldHab = params['NUMBER_HABITANTS']

        feedback = QgsProcessingMultiStepFeedback(totalStpes, feedback)

        if not OPTIONAL_GRID_INPUT: params['CELL_SIZE'] = P_CELL_SIZE
        grid, isStudyArea = buildStudyArea(params['CELL_SIZE'], params['BLOCKS'],
                                         params['STUDY_AREA_GRID'],
                                         context, feedback)
        gridNeto = grid  


        steps = 0 + 1
        feedback.setCurrentStep(steps)


        pathCsvVivienda = params['CENSO_VIVIENDA']
        file = pathCsvVivienda
        cols = ['I01', 'I02', 'I03', 'I04', 'I05', 'I06', 'I09', 'I10', 'V02', 'V04', 'V06']
        df = pd.read_csv(file, usecols=cols)

        # fix codes 
        df['I01'] = df['I01'].astype(str)
        df['I02'] = df['I02'].astype(str)
        df['I03'] = df['I03'].astype(str)
        df['I04'] = df['I04'].astype(str)
        df['I05'] = df['I05'].astype(str)
        df['I06'] = df['I06'].astype(str)
        df['I09'] = df['I09'].astype(str)
        df['I10'] = df['I10'].astype(str)

        df.loc[df['I01'].str.len() < 2, 'I01'] = "0" + df['I01']
        df.loc[df['I02'].str.len() < 2, 'I02'] = "0" + df['I02']
        df.loc[df['I03'].str.len() < 2, 'I03'] = "0" + df['I03']
        df.loc[df['I04'].str.len() == 1, 'I04'] = "00" + df['I04']
        df.loc[df['I04'].str.len() == 2, 'I04'] = "0" + df['I04']
        df.loc[df['I05'].str.len() == 1, 'I05'] = "00" + df['I05']
        df.loc[df['I05'].str.len() == 2, 'I05'] = "0" + df['I05']
        df.loc[df['I06'].str.len() < 2, 'I06'] = "0" + df['I06']
        df.loc[df['I09'].str.len() == 1, 'I09'] = "00" + df['I09']
        df.loc[df['I09'].str.len() == 2, 'I09'] = "0" + df['I09']
        df.loc[df['I10'].str.len() < 2, 'I10'] = "0" + df['I10']

        df['codman'] = df['I01'].astype(str) + df['I02'].astype(str) + df['I03'].astype(str) \
                      + df['I04'].astype(str) + df['I05'].astype(str) + df['I06'].astype(str)


        #Para el cálculo se utilizan los datos de las cubiertas,
        # pareds y pisos en estado MALO según el Censo de pobalción y vivienda 2010.
        # V02: categoría 3 (techo). 
        # V04: categoría 3 (paredes). 
        # V06: categoría 3 (piso).

        df['pt'] = 1.0
        df['vivcarencias'] = 0.0
        df.loc[(df['V02'] == '3')
             & (df['V04'] == '3')
             & (df['V06'] == '3')       
               ,'vivcarencias'] = 1.0



        df['pt'] = df['pt'].astype(float)
        df['vivcarencias'] = df['vivcarencias'].astype(float)


        aggOptions = {
                      'codman' : 'first',
                      'pt' : 'count',
                      'vivcarencias' : 'sum',
                     } 


        resManzanas = df.groupby('codman').agg(aggOptions)

        resManzanas['pobconcaren'] = None
        resManzanas['pobconcaren'] = (resManzanas['vivcarencias'] / resManzanas['pt']) * 100   


        df = resManzanas     


        steps += 1
        feedback.setCurrentStep(steps)

        outputCsv = self.CURRENT_PATH+'/pobconcaren.csv'
        feedback.pushConsoleInfo(str(('pobconcaren en ' + outputCsv)))
        df.to_csv(outputCsv, index=False)

        steps += 1
        feedback.setCurrentStep(steps)

        if exitCsv := os.path.exists(outputCsv):
            print("El archivo CSV existe")
        else:
            print("No se encuentra CSV")

        CSV =  QgsVectorLayer(outputCsv, "csv", "ogr")
        featuresCSV = CSV.getFeatures()
        # fields = layer.dataProvider().fields()
        field_names = [field.name() for field in CSV.fields()]
        print(field_names)            

        steps += 1
        feedback.setCurrentStep(steps)

        steps += 1
        feedback.setCurrentStep(steps)
        result = joinByAttr2(params['BLOCKS'], fieldDpaMan,
                                outputCsv, 'codman',
                                [],
                                UNDISCARD_NONMATCHING,
                                '',
                                1,
                                context,
                                feedback)

        steps += 1
        feedback.setCurrentStep(steps)
        expressionNotNull = "pobconcaren IS NOT '' AND pobconcaren is NOT NULL"
        notNull =   filterByExpression(result['OUTPUT'], expressionNotNull, context, feedback) 


        steps += 1
        feedback.setCurrentStep(steps)
        formulaDummy = 'pobconcaren * 1.0'
        result = calculateField(notNull['OUTPUT'], 
                                 'pobconcaren_n',
                                 formulaDummy,
                                 context,
                                 feedback)  


  # ----------------------CONVERTIR A NUMERICOS --------------------     

        steps += 1
        feedback.setCurrentStep(steps)
        formulaDummy = 'vivcarencias * 1.0'
        result = calculateField(result['OUTPUT'], 
                                 'vivcarencias_n',
                                 formulaDummy,
                                 context,
                                 feedback)  

        steps += 1
        feedback.setCurrentStep(steps)
        formulaDummy = 'pt * 1.0'
        result = calculateField(result['OUTPUT'], 
                                 'pt_n',
                                 formulaDummy,
                                 context,
                                 feedback)          


       # ----------------------PROPORCIONES AREA--------------------------

        steps += 1
        feedback.setCurrentStep(steps)
        blocks = calculateArea(result['OUTPUT'], 'area_bloc', context,
                               feedback)     

        steps += 1
        feedback.setCurrentStep(steps)
        segments = intersection(blocks['OUTPUT'], gridNeto['OUTPUT'],
                                ['vivcarencias_n','pt_n','area_bloc'],
                                ['id_grid','area_grid'],
                                context, feedback)        

        steps += 1
        feedback.setCurrentStep(steps)
        segmentsArea = calculateArea(segments['OUTPUT'],
                                     'area_seg',
                                     context, feedback)

        # -------------------------PROPORCIONES VALORES-------------------------

        steps += 1
        feedback.setCurrentStep(steps)
        formulaDummy = '(area_seg/area_bloc) * vivcarencias_n'
        result = calculateField(segmentsArea['OUTPUT'], 'vivcarencias_n_seg',
                                               formulaDummy,
                                               context,
                                               feedback)     

        steps += 1
        feedback.setCurrentStep(steps)
        formulaDummy = '(area_seg/area_bloc) * pt_n'
        result = calculateField(result['OUTPUT'], 'pt_n_seg',
                               formulaDummy,
                               context,
                               feedback)   


        steps += 1
        feedback.setCurrentStep(steps)
        result = makeSureInside(result['OUTPUT'],
                                context,
                                feedback)                                    

        #----------------------------------------------------------------------   

        steps += 1
        feedback.setCurrentStep(steps)
        result = joinByLocation(gridNeto['OUTPUT'],
                             result['OUTPUT'],
                             ['vivcarencias_n_seg','pt_n_seg'],                                   
                              [CONTIENE], [SUM],
                              UNDISCARD_NONMATCHING,
                              context,
                              feedback)  


        steps += 1
        feedback.setCurrentStep(steps)
        formulaDummy = '(vivcarencias_n_seg_sum/pt_n_seg_sum) * 100'
        result = calculateField(result['OUTPUT'], NAMES_INDEX['ID02'][0],
                               formulaDummy,
                               context,
                               feedback, params['OUTPUT'])



        # steps = steps+1
        # feedback.setCurrentStep(steps)
        # gridNeto = joinByLocation(gridNeto['OUTPUT'],
        #                      result['OUTPUT'],
        #                      ['pobconcaren_n'],                                   
        #                       [INTERSECTA], [MEDIA],
        #                       UNDISCARD_NONMATCHING,
        #                       context,
        #                       feedback)         


        # fieldsMapping = [
        #     {'expression': '"id_grid"', 'length': 10, 'name': 'id_grid', 'precision': 0, 'type': 4}, 
        #     {'expression': '"area_grid"', 'length': 16, 'name': 'area_grid', 'precision': 3, 'type': 6}, 
        #     {'expression': '"acceso_inter_n_mean"', 'length': 20, 'name': NAMES_INDEX['ID02'][0], 'precision': 2, 'type': 6}
        # ]      

        # steps = steps+1
        # feedback.setCurrentStep(steps)
        # result = refactorFields(fieldsMapping, gridNeto['OUTPUT'], 
        #                         context,
        #                         feedback, params['OUTPUT'])                                                                

        return result
          
    def icon(self):
        return QIcon(os.path.join(pluginPath, 'housebroken.png'))

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'D02 Viviendas con carencias constructivas'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'D Dinámicas socio-espaciales'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ID02HomesConstructiveDeficiencies()

    def shortHelpString(self):
        return  "<b>Descripción:</b><br/>"\
                "<span>Mide el porcentaje de viviendas que presentan carencias constructivas. Se define carencia constructiva cuando el estado de la cubierta, paredes y piso presentan deterioro o daño estructural que son un peligro inminente para los habitantes de la vivienda.</span>"\
                "<br/><br/><b>Justificación y metodología:</b><br/>"\
                "<span>Para el cálculo se utilizan los datos de las cubiertas, pareds y pisos en estado MALO según el Censo de pobalción y vivienda 2010. CPV 2010: V02: categoría 3 (techo). V04: categoría 3 (paredes). V06: categoría 3 (piso).</span>"\
                "<br/><br/><b>Formula:</b><br/>"\
                "<span>(Viviendas con carencias / Total de viviendas)*100<br/>"