# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Sisurbano
                                 A QGIS plugin
 Cáculo de indicadores urbanos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-16
        copyright            : (C) 2019 by LlactaLAB
        email                : johnatan.astudillo@ucuenca.edu.ec
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Johnatan Astudillo'
__date__ = '2019-09-16'
__copyright__ = '(C) 2019 by LlactaLAB'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsProcessingMultiStepFeedback,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSink)
from .ZProcesses import *
from .Zettings import *

pluginPath = os.path.split(os.path.split(os.path.dirname(__file__))[0])[0]

class ZN05AllocateValuesForArea(QgsProcessingAlgorithm):
    """
    Distribuye la población de las manzanas a los puntos o medidores
    más cercanos al polígono de la manzana
    """  
    INPUT_POLYGON = 'INPUT_POLYGON'
    FIELD_CATEGORIES = 'FIELD_CATEGORIES'
    OUTPUT = 'OUTPUT'
    STUDY_AREA_GRID = 'STUDY_AREA_GRID'

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT_POLYGON,
                self.tr('Polígonos'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.FIELD_CATEGORIES,
                self.tr('Categorías'),
                'Tipologia', 'INPUT_POLYGON'
            )
        )        
       
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.STUDY_AREA_GRID,
                self.tr(TEXT_GRID_INPUT),
                [QgsProcessing.TypeVectorPolygon],
                '', OPTIONAL_GRID_INPUT
            )
        )        

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Salida')
            )
        )

    def processAlgorithm(self, params, context, feedback):
        steps = 0
        totalStpes = 6
        fieldCategories = params['FIELD_CATEGORIES']


        feedback = QgsProcessingMultiStepFeedback(totalStpes, feedback)    

        if not OPTIONAL_GRID_INPUT: params['CELL_SIZE'] = P_CELL_SIZE
        grid, isStudyArea = buildStudyArea(params['CELL_SIZE'], params['INPUT_POLYGON'],
                                         params['STUDY_AREA_GRID'],
                                         context, feedback)


        gridNeto = grid

        steps = steps+1
        feedback.setCurrentStep(steps)
        segments = intersection(params['INPUT_POLYGON'], gridNeto['OUTPUT'],
                                [fieldCategories],
                                ['id_grid'],
                                context, feedback)


        steps = steps+1
        feedback.setCurrentStep(steps)
        segmentsArea = calculateArea(segments['OUTPUT'],
                                     'area_seg',
                                     context, feedback)


        steps = steps+1
        feedback.setCurrentStep(steps)
        segmentsSure = makeSureInside(segmentsArea['OUTPUT'],
                                                    context,
                                                    feedback)


        steps = steps+1
        feedback.setCurrentStep(steps)
        formulaMayorArea = 'case when area_seg / maximum(area_seg, group_by:=id_grid) is 1 then 1 else 0 end'
        polygonIsAndNotArea = calculateField(segmentsSure['OUTPUT'], 'ismax',
                                               formulaMayorArea,
                                               context,
                                               feedback)

        steps = steps+1
        feedback.setCurrentStep(steps)
        filterOnlyMax = 'ismax is 1'
        onlyMaxArea = filterByExpression(polygonIsAndNotArea['OUTPUT'],
                                               filterOnlyMax,
                                               context,
                                               feedback)

        steps = steps+1
        feedback.setCurrentStep(steps)
        result = joinByLocationNotSummary(gridNeto['OUTPUT'],
                                         onlyMaxArea['OUTPUT'],
                                         [fieldCategories],                                   
                                          [CONTIENE],
                                          UNDISCARD_NONMATCHING, 1,
                                          context,
                                          feedback, params['OUTPUT'])         


        return result    

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        #return {self.OUTPUT: dest_id}
                                          
    def icon(self):
        return QIcon(os.path.join(pluginPath, 'sisurbano', 'icons', 'manyInv.png'))

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Z05 Asignar categoría con mayor área'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Z General'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ZN05AllocateValuesForArea()

    def shortHelpString(self):
        return  "<b>Descripción:</b><br/>"\
                "<span>Asigna a la malla la categoría con mayor área intersectada entre la capa malla y la capa de polígonos que cotiene las categorías.</span>"