# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sisurbano
                                 A QGIS plugin
 Cáculo de indicadores urbanos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-16
        copyright            : (C) 2019 by LlactaLAB
        email                : johnatan.astudillo@ucuenca.edu.ec
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'LlactaLAB'
__date__ = '2019-09-16'
__copyright__ = '(C) 2019 by LlactaLAB'


# import sys, os
# import subprocess


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sisurbano class from file Sisurbano.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sisurbano import SisurbanoPlugin
    # print("Agregando pandas")
    # dir = str(os.path.join(os.path.dirname(os.path.realpath(__file__)), ''))
    # dir = str(os.path.join(dir, 'libs'))
    # dir = str(os.path.join(dir, 'pandas'))
    # print(dir)
    # sys.path.insert(0, dir)
    return SisurbanoPlugin()
